services:
  postgres:
    image: postgres:16
    container_name: de_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      - ./sql:/sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: de_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "True"
      DATA_DIR: /data

    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    restart: unless-stopped

  airflow:
#    image: apache/airflow:2.9.3
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: project_itde_airflow:2.9.3-pyspark
    env_file: .env
    container_name: de_airflow
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "change_me_to_any_long_random_string"
      AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "true"
      AIRFLOW_CONN_DE_POSTGRES: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW_CONN_SPARK_DEFAULT: spark://local
      AIRFLOW_USER: ${AIRFLOW_USER:-airflow}
      AIRFLOW_PASSWORD: ${AIRFLOW_PASSWORD:-airflow}

    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
#      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/data
    restart: unless-stopped



#  loader:
#    profiles: ["tools"]
#    image: python:3.11-slim
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_HOST: postgres
#      POSTGRES_PORT: "5432"
#    volumes:
#      - ./data:/data:ro
#      - ./scripts:/app:ro
#    working_dir: /app
#    command: bash -lc "pip -q install pandas pyarrow sqlalchemy psycopg2-binary && python load_raw.py"

volumes:
  pgdata:
  pgadmin_data:
